version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - main
      - canteen_menu
      - exit_notes
      - knowledge_base
      - news
      - schedules
      - suggestoins
      - users
  db:
    build: .
    container_name: my_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: prestige_database
      POSTGRES_USER: ${LOGIN}
      POSTGRES_PASSWORD: ${PASSWORD}
  main:
    build: ./services/main
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  canteen_menu:
    build: ./services/canteen_menu
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  exit_notes:
    build: ./services/exit_notes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  knowledge_base:
    build: ./services/knowledge_base
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  news:
    build: ./services/news
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  schedules:
    build: ./services/schedules
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  suggestions:
    build: ./services/suggestions
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  users:
    build: ./services/users
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
