networks:
  db-network:
    driver: bridge
  nginx-network:
    driver: bridge
  
services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      - db
    networks:
    - db-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - main
      - canteen_menu
      - exit_notes
      - knowledge_base
      - news
      - schedules
      - suggestions
      - users 
    networks:
    - nginx-network

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - db-network


  main:
    build: ./services/main
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
    - db-network
    - nginx-network


  canteen_menu:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET-KEY=${CANTEEN_MENU_SECRET_KEY}
    build: ./services/canteen_menu
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network


  exit_notes:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: ./services/exit_notes
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network


  knowledge_base:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: ./services/knowledge_base
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network


  news:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: ./services/news
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network



  schedules:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: ./services/schedules/
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network



  suggestions:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: ./services/suggestions
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network


  users:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: ./services/users
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db-network
      - nginx-network



volumes:
  postgres_data:
  esdata:
