networks:
  menu-db-network:
    driver: bridge
  exit-notes-db-network:
    driver: bridge
  knowledge-base-db-network:
    driver: bridge
  news-db-network:
    driver: bridge
  schedules-db-network:
    driver: bridge
  suggestions-db-network:
    driver: bridge
  users-db-network:
    driver: bridge
  nginx-network:
    driver: bridge
  
services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      - knowledge_base_db
    networks:
    - nginx-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - canteen_menu_db
      - exit_notes_db
      - knowledge_base_db
      - news_db
      - schedules_db
      - suggestions_db
      - users_db
      - main
      - canteen_menu
      - exit_notes
      - knowledge_base
      - news
      - schedules
      - suggestions
      - users 
    networks:
    - nginx-network

  main:
    build: ./services/main
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    volumes:
      - .:/app
    networks:
    - nginx-network
    - users-db-network


  canteen_menu:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/canteen_menu
    volumes:
      - .:/app
    depends_on:
      - canteen_menu_db
    networks:
      - menu-db-network
      - nginx-network
  canteen_menu_db:
    image: postgres
    restart: always
    volumes:
      - canteen_menu_postgres_data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - menu-db-network

  exit_notes:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/exit_notes
    volumes:
      - .:/app
    depends_on:
      - exit_notes_db
    networks:
      - exit-notes-db-network
      - nginx-network
  exit_notes_db:
    image: postgres
    restart: always
    volumes:
      - exit_notes_postgres_data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - exit-notes-db-network

  knowledge_base:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/knowledge_base
    volumes:
      - .:/app
    depends_on:
      - knowledge_base_db
    networks:
      - knowledge-base-db-network
      - nginx-network
  knowledge_base_db:
    image: postgres
    restart: always
    volumes:
      - knowledge_base_postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - knowledge-base-db-network

  news:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/news
    volumes:
      - .:/app
    depends_on:
      - news_db
    networks:
      - news-db-network
      - nginx-network
  news_db:
    image: postgres
    restart: always
    volumes:
      - news_postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - news-db-network

  schedules:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/schedules/
    volumes:
      - .:/app
    depends_on:
      - schedules_db
      - users
    networks:
      - schedules-db-network
      - nginx-network
  schedules_db:
    image: postgres
    restart: always
    volumes:
      - schedules_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - schedules-db-network


  suggestions:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/suggestions
    depends_on:
      - suggestions_db
    networks:
      - suggestions-db-network
      - nginx-network
  suggestions_db:
    image: postgres
    restart: always
    volumes:
      - suggestions_postgres_data:/var/lib/postgresql/data
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - suggestions-db-network


  users:
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_STATE=${DEBUG_STATE}
      - HTTP_HOST=${HTTP_HOST}
    build: ./services/users
    volumes:
      - .:/app
    depends_on:
      - users_db
    networks:
      - users-db-network
      - nginx-network
  users_db:
    image: postgres
    restart: always
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prestige_database
    networks:
    - users-db-network

volumes:
  canteen_menu_postgres_data:
  exit_notes_postgres_data:
  knowledge_base_postgres_data:
  schedules_postgres_data:
  suggestions_postgres_data:
  news_postgres_data:
  users_postgres_data:
  for_voulonteers_postgres_data:
  esdata:

